### ISSUE TITLE
`update_terrain_cell` not updating cells?

### ISSUE THREAD

**Issue by Atlinx** [Portponky/better-terrain-gde#1]
I originally used the gdscript version of BetterTerrain to place and update terrain tiles, which worked fine. However, after replacing my code to use `BetterTerrainPP` objects, `update_terrain_cell` no longer updates the terrain.

My new code looks something like this (although I'm not 100% sure if this is the correct way due to a lack of documentation):
```gdscript
@export var tile_map: TileMap

var better_tile_map = BetterTerrainPP.new()

func _ready():
    better_tile_map.init(tile_map)
    # Setting and updating cells
    better_tile_map.set_cell(1, Vector2i.ZERO, 1)
    better_tile_map.update_terrain_cell(1, Vector2i.ZERO)
```

I'm using the terrain within a custom map editor that lets you paint tiles onto a canvas with brushes of different sizes. When using the GDExtension version of BetterTerrain, it seems to only be updating the terrain in a 2x2 chunk from (0,0) to (1,1):

![image](https://github.com/Portponky/better-terrain-gde/assets/25368491/647c2838-e9bb-4ebd-994c-7298c4fbabc2)

**Comment by Atlinx** [comment]
This seems to be an issue with `update_terrain_cell` specifically. I was able to get it to work by using `update_terrain_area` instead.

```gdscript
# This doesn't work
better_tile_map.update_terrain_cell(layer, position)
# This works
better_tile_map.update_terrain_area(layer, Rect2i(position, Vector2i.ONE))
```

**Comment by Portponky** [comment]
Ah hi, the assignment in the cell functions is wrong at https://github.com/Portponky/better-terrain-gde/blob/9aea11aa3ccb566c65974f84d4608a0b9ee42231/src/BetterTerrainPP.cpp#L367 I'll fix this when I have time.
