### ISSUE TITLE
`set_cell` fails to set a specific terrain

### ISSUE THREAD

**Issue by Atlinx** [Portponky/better-terrain-gde#3]
For some reason, the individual tile type for my wood plank wall terrain is not getting tiled by the gde version of better terrain.  This works with the regular gdscript version of better-terrain. I also tried removing all tiles except for the individual tile type. This results in no tile getting placed by `set_cell`.

![image](https://github.com/Portponky/better-terrain-gde/assets/25368491/1d54ac19-c8a8-4756-9669-dfed85d22032)

**Comment by Portponky** [comment]
Can you post a code snippet, and your terrain set up?

**Comment by Atlinx** [comment]
I suspect the terrain data is not getting fully read into the gdextension.

**Comment by Atlinx** [comment]
Here's my code snippet
```gdscript
var _better_tile_map: BetterTerrainPP
var tile_map: TileMap

func _set_and_update_cell(layer: int, position: Vector2i, terrain_id: int, update: bool = true):
	if _has_gdextension:
		_better_tile_map.set_cell(layer, position, terrain_id)
		if update:
			_better_tile_map.update_terrain_cell(layer, position)
	else:
		BetterTerrain.set_cell(tile_map, layer, position, terrain_id)
		if update:
			BetterTerrain.update_terrain_cell(tile_map, layer, position)
```

Here's the tileset tres file

[hd_tileset.zip](https://github.com/Portponky/better-terrain-gde/files/14128334/hd_tileset.zip)

I'm going to try to narrow it down more since it's weird that only this terrain (which is the 3rd terrain) is acting weird.

**Comment by Atlinx** [comment]
It seems to be strictly tied to the third terrain slot. If I shuffle the ordering of the tiles, the 3rd terrain always encounters this problem.

![image](https://github.com/Portponky/better-terrain-gde/assets/25368491/dd05f1f0-9ef8-4398-a957-a98be8cd3b35)
