### ISSUE TITLE
Decorations are not applied

### ISSUE THREAD

**Issue by tvenclovas96** [Portponky/better-terrain-gde#5]
Decorations are not applied using the GDextension version of the plugin compared to the GDscript version, even if using an identical array of tiles.

As far as I can tell, two issues cause this in the block below. Tiles eligible for decorations are empty tiles and accordingly marked as `Terraintype::EMPTY`, which is equal to `-1`
```cpp
void BetterTerrainPP::update_tile_immediate(int layer, godot::Vector2i coord, const std::map<godot::Vector2i, int>& types)
{
  int type = map_safe_get(types, coord, -1);
  if (type < TerrainType::EMPTY || type >= m_terrain_types.size())
    return;

  const Placement* placement {nullptr};
  if (m_terrain_types[type] == TerrainType::MATCH_TILES || m_terrain_types[type] == TerrainType::DECORATION)
    placement = update_tile_tiles(coord, types, m_terrain_types[type] == TerrainType::DECORATION);
...
```
First, the return type of `m_terrain_types.size()` as an std::vector is `size_t`, causing `type >= m_terrain_types.size()` to always equate to true when `type < 0`, atleast compiled with MSVC,  skipping evaluation of empty tiles. I'm guessing `type` is casted to an unsigned integer with the bits intact, creating an absurdly large number. Casting `m_terrain_types.size()` to `int` fixes this.

Second, `m_terrain_types` doesn't appear to hold `TerrainType::DECORATION`, so decorations are never checked for.
I worked around this be replacing `m_terrain_types[type] == TerrainType::DECORATION` for `type == TerrainType::EMPTY`, which allows the tiles to be evaluated, but I don't know if this is a good idea to do.
With both changes decorations are once again added similarly to the GDscript version.

**Comment by Portponky** [comment]
Looks like you're right. I think there are a few changes that need to be synced between the gdscript version and the gde version. I'm rather busy at the moment, but I'll take a look at this again some time in May and will fix decorations and other minor issues. Great spot with the size type casting.

**Comment by Portponky** [comment]
Hello again! I have fixed the decorations (and tile set scene sources, if anyone cares). Evaluating type as TerrainType::EMPTY is sufficient, but it has to be done such that `m_terrain_types[type]` is not evaluated if it is empty. Once I've tested the build I will close this issue. Sorry for the long delay, I've been really busy this last while.

**Comment by Portponky** [comment]
Seems good, closing.
