### ISSUE TITLE
Memory leak when calling `update_terrain_cell`

### ISSUE THREAD

**Issue by Atlinx** [Portponky/better-terrain-gde#6]
The GDE version of better-terrain causes a memory leak when calling `BetterTerrain.update_terrain_cell` repeatedly. This does not happen with the gdscript version of the plugin.

**Comment by Atlinx** [comment]
It seems to be caused by accessing a field in the td_meta Dictionary. Might be related to this: https://github.com/godotengine/godot-cpp/issues/1240

**Comment by Portponky** [comment]
Good find, thanks.
